version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - 9100
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge