global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['IP:9090'] ## IP Address of the Machine
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['IP:9100'] ## IP Address of the Machine