global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node_exporter:9100']